### ISSUE TITLE
Clean UP & Dockerization eos3xip

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos3xip#1]

**Comment by GemmaTuron** [comment]
@samuelmaina 
Before concluding this model, please make sure the checkpoints of the model are in the right folder

**Comment by samuelmaina** [comment]
Hello @GemmaTuron ,
The model has many folders with models artifacts(.pt files, .csv and other formats) . I tried to refactor it but it was throwing many errors which required v inner modification of code. I will look into it after I am done with the current issues.

**Comment by GemmaTuron** [comment]
Hello @samuelmaina 
The checkpoints is the finetune/qm8. It should just be a matter of moving it and pointing the paths to the correct directory

**Comment by samuelmaina** [comment]
I thought I also needed to move  the example data (model/framework/code/grover/exampledata). I will move change `finetune/qm8` path.

**Comment by samuelmaina** [comment]
Okay @GemmaTuron , 
I will change I will move change `finetune/qm8` path. What about the example data (model/framework/code/grover/exampledata)?

**Comment by GemmaTuron** [comment]
The checkpoints are the `.pt` files. I think the example data is not used anywhere and can be deleted
